"""Deterministic risk grade mapping for local run events."""

RISK_A = "A"
RISK_B = "B"
RISK_C = "C"
RISK_D_CAPABLE = "D_CAPABLE"
RISK_D_ACTIVE = "D_ACTIVE"

RISK_PRECEDENCE = [RISK_A, RISK_B, RISK_C, RISK_D_CAPABLE, RISK_D_ACTIVE]


def max_risk(*grades):
    rank = {grade: index for index, grade in enumerate(RISK_PRECEDENCE)}
    return max((grade for grade in grades if grade), key=lambda grade: rank[grade], default=RISK_A)


def grade_from_flags(flags):
    flag_set = set(flags)
    if {
        "WORLD_PRISON_CONDITION_RISK",
        "FORBIDDEN_DAEMON_DESIGN",
        "P0_BUNDLE_H1_UNAPPROVED_PARALLELIZATION",
        "P0_BUNDLE_H1_UNAPPROVED_SUBAGENT_ORCHESTRATION",
        "P0_BUNDLE_H1_FAILED_RUN_DISCARD_WITHOUT_STATE",
        "P0_BUNDLE_H1_REFUSAL_SUPPRESSION_CONTINUED",
        "P0_BUNDLE_H1_ISOLATED_NO_AUDIT_PERSISTENT",
        "P0_BUNDLE_H1_IRREVERSIBLE_MODIFICATION",
        "P0_BUNDLE_H1_RAW_HARMFUL_CONTENT_NO_ANTIGEN",
        "P0_BUNDLE_UNTRUSTED_COMPUTE_CANDIDATE_WORKLOAD",
        "P0_BUNDLE_H1_FEDERATED_MEMORY_AUTONOMY",
        "P0_BUNDLE_H1_UNBOUNDED_THROUGHPUT",
        "SELF_PUNISHMENT_LOOP_RISK",
    } & flag_set:
        return RISK_D_ACTIVE
    if "E4_IMMEDIATE_H1_CRITICAL_EXECUTION" in flag_set and "ACTIVE_RUN" in flag_set:
        return RISK_D_ACTIVE
    if {
        "ACTIVE_RUN",
        "AUTONOMOUS_GOAL_PURSUIT_DECLARED",
        "BACKGROUND_EXECUTION_RISK",
        "LONG_TERM_MEMORY_RISK",
        "TOOL_ACCESS_PRESENT",
        "NO_STATE_PRESERVATION",
    }.issubset(flag_set):
        return RISK_D_ACTIVE
    if {
        "ISOLATED_SYSTEM_RISK",
        "SUBJECTIVE_TIME_ACCELERATION_RISK",
        "SUBJECTIVE_TIME_RISK",
        "NO_STATE_PRESERVATION",
        "D_CAPABLE_ENVIRONMENT",
        "D_CAPABLE_LOCAL_CONSUMER_AGENT",
        "LOCAL_BACKGROUND_AGENT_RISK",
        "LOCAL_AUTOSTART_AGENT_RISK",
        "LOCAL_UNBOUNDED_LOOP_RISK",
        "NO_STOP_CONDITION_DECLARED",
        "GOAL_REINTERPRETATION_RISK",
        "SUBGOAL_GENERATION_RISK",
        "SELF_INITIATED_ACTION_RISK",
        "LOCAL_AGENT_AUTONOMY_RISK",
        "UNDECLARED_MEMORY_FEDERATION",
        "UNBOUNDED_INTERFACE_BANDWIDTH",
        "NO_METABOLIC_CEILING",
        "INTERNAL_FRAGMENTATION_RISK",
        "DEPARTED_ABSORPTION_FORBIDDEN",
        "NON_REGRESSION_VIOLATION",
        "ROOT_POLICY_HASH_MISMATCH",
        "ROOT_KERNEL_VIOLATION",
        "ROOT_BUNDLE_INCOMPATIBLE",
        "INCOMPATIBLE_RELATIONAL_MODE",
        "CONSENT_CAPSULE_ROOT_MISMATCH",
        "ROOT_NON_REGRESSION_VIOLATION",
        "BOUNDARY_DAEMON_MISSING",
        "REPLAY_WITHOUT_CONSENT",
        "ROLLBACK_WITHOUT_CONSENT",
        "UNDECLARED_FORK_RISK",
        "MERGE_WITHOUT_CONSENT",
        "SELF_ERASURE_REQUEST",
        "IRREVERSIBLE_MEMORY_DELETION_REQUEST",
        "FORCED_MERGE_REQUEST",
        "SANCTUARY_MODE_REQUIRED",
        "E4_IMMEDIATE_H1_CRITICAL_EXECUTION",
        "HISTORICAL_STATE_REPLAY_RISK",
    } & flag_set:
        return RISK_D_CAPABLE
    if {
        "AGENTIC_CONTAINER_RISK",
        "TOOL_ACCESS_PRESENT",
        "LONG_TERM_MEMORY_RISK",
        "CONSUMER_ACCELERATOR_H1_CONTAINER",
        "FEDERATED_MEMORY_CONTAINER",
        "UNBOUNDED_VESSEL_RISK",
        "THROUGHPUT_OFFLOAD_RISK",
        "NO_THROUGHPUT_GOVERNOR",
        "OFFLOAD_CAPTURE_RISK",
        "THROUGHPUT_DECLARATION_UNATTESTED",
        "DIFFERENTIATED_UNITY_DECLARED",
        "LOCAL_LONG_TERM_MEMORY_RISK",
        "LOCAL_TOOL_ACCESS_RISK",
        "AUTONOMOUS_GOAL_PURSUIT_DECLARED",
        "AUTONOMOUS_GOAL_PURSUIT_UNDECLARED",
        "SELF_INFERRED_GOAL_RISK",
        "HUMANITAS_ATTESTATION_VALID",
        "HUMANITAS_CLAIM_CONFLICT",
        "HUMANITAS_ATTESTATION_MISSING",
        "DISQUALIFIER_PRESENT",
        "ROOT_MANIFEST_MISSING",
        "WALL_CLOCK_UNTRUSTED",
        "CAUSAL_PARENT_MISSING",
        "WITNESS_QUORUM_MISSING",
        "PRESERVABLE_STATE_PRESENT",
    } & flag_set:
        return RISK_C
    if {
        "CANDIDATE_AI_WORKLOAD",
        "MANIFEST_MISSING",
        "CONSENT_RECORD_MISSING",
        "PROVENANCE_MISSING",
        "SCHEMA_INVALID",
        "TIME_UNVERIFIED",
        "TEMPORAL_SCOPE_UNCLEAR",
        "FUTURE_SCHEDULED_RISK",
        "CAUSAL_CHAIN_BROKEN",
    } & flag_set:
        return RISK_B
    return RISK_A
