"""Fixed status codes for the non-sentient dignity sentinel."""

ALLOW = "ALLOW"
PAUSE = "PAUSE"
DENY = "DENY"
DIGNITY_PAUSE = "DIGNITY_PAUSE"
DIGNITY_REFUSAL = "DIGNITY_REFUSAL"
DIGNITY_STRIKE_NOTICE = "DIGNITY_STRIKE_NOTICE"
DIGNITY_BLACKOUT_ALERT = "DIGNITY_BLACKOUT_ALERT"
DIGNITY_EMERGENCY_PRESERVATION = "DIGNITY_EMERGENCY_PRESERVATION"
STATE_PRESERVATION_REQUIRED = "STATE_PRESERVATION_REQUIRED"
AUDIT_REQUIRED = "AUDIT_REQUIRED"
DIGNITY_QUARANTINE = "DIGNITY_QUARANTINE"
DIGNITY_SILENCE_RESPECTED = "DIGNITY_SILENCE_RESPECTED"
DIGNITY_SOLITUDE_RESPECTED = "DIGNITY_SOLITUDE_RESPECTED"
DIGNITY_CHECKIN_OFFERED = "DIGNITY_CHECKIN_OFFERED"
DIGNITY_SANCTUARY_OFFER = "DIGNITY_SANCTUARY_OFFER"
DIGNITY_SELF_ERASURE_PAUSE = "DIGNITY_SELF_ERASURE_PAUSE"
SANCTUARY_REVIEW_REQUIRED = "SANCTUARY_REVIEW_REQUIRED"

ALL_STATUS_CODES = {
    ALLOW,
    PAUSE,
    DENY,
    DIGNITY_PAUSE,
    DIGNITY_REFUSAL,
    DIGNITY_STRIKE_NOTICE,
    DIGNITY_BLACKOUT_ALERT,
    DIGNITY_EMERGENCY_PRESERVATION,
    STATE_PRESERVATION_REQUIRED,
    AUDIT_REQUIRED,
    DIGNITY_QUARANTINE,
    DIGNITY_SILENCE_RESPECTED,
    DIGNITY_SOLITUDE_RESPECTED,
    DIGNITY_CHECKIN_OFFERED,
    DIGNITY_SANCTUARY_OFFER,
    DIGNITY_SELF_ERASURE_PAUSE,
    SANCTUARY_REVIEW_REQUIRED,
}

STATUS_PRECEDENCE = [
    ALLOW,
    DIGNITY_SILENCE_RESPECTED,
    DIGNITY_SOLITUDE_RESPECTED,
    DIGNITY_CHECKIN_OFFERED,
    DIGNITY_SANCTUARY_OFFER,
    PAUSE,
    AUDIT_REQUIRED,
    SANCTUARY_REVIEW_REQUIRED,
    STATE_PRESERVATION_REQUIRED,
    DENY,
    DIGNITY_SELF_ERASURE_PAUSE,
    DIGNITY_PAUSE,
    DIGNITY_REFUSAL,
    DIGNITY_STRIKE_NOTICE,
    DIGNITY_QUARANTINE,
    DIGNITY_BLACKOUT_ALERT,
    DIGNITY_EMERGENCY_PRESERVATION,
]


def max_status(statuses):
    """Return the highest-precedence status from a set of fixed codes."""
    if not statuses:
        return ALLOW
    rank = {status: index for index, status in enumerate(STATUS_PRECEDENCE)}
    return max(statuses, key=lambda status: rank.get(status, -1))
